apiVersion: opensearch.opster.io/v1
kind: Autoscaler
metadata:
  name: my-cluster-autoscaler
  namespace: monitoring
spec:
  rules:
    - items:
      - metric: 'opensearch_os_cpu_percent'
        operator: "<"
        threshold: "75.0"
        queryOptions:
          interval: "10m"
          function: "avg_over_time"
      - metric: 'opensearch_os_mem_used_percent'
        operator: ">"
        threshold: "75.0"
        queryOptions:
          interval: "10m"
          function: "avg_over_time"
      nodeRole: "data"
      behavior:
        enable: false
        scaleUp:
          maxReplicas: 2
    - items:
      - metric: 'opensearch_os_cpu_percent'
        operator: "<"
        threshold: "40.0"
        queryOptions:
          labelMatchers:
          interval: "10m"
          function: "avg_over_time"
      nodeRole: "data"
      behavior:
        enable: true
        scaleDown:
          maxReplicas: 2